name: ml-st
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.10
  - numpy==1.26.4
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - jupyterlab==4.2.5
  - matplotlib==3.9.2
  - pandas==2.2.2
  - seaborn==0.13.2
